$(document).ready(function(){
        $('input[type="checkbox"]').click(function(){
            if($(this).attr("value")=="wantKnowledge"){
                $(".knowledge").toggle();
            }
            if($(this).attr("value")=="wantTopics"){
                $(".topics").toggle();
            }
        });
});